version: '3'

services:
  frontend-gestion-facture:
    image: gestion-facture:front
    container_name: Facturefrontend
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "80:80"
    networks:
      - gestion_facturation_api-network

networks:
  gestion_facturation_api-network:
    external: true
